import Head from "next/head";
import Abaut from "../components/Abaut";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
// import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seba Zwenger | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Abaut />
    </div>
  );
}
