import Head from "next/head";
// import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seba Zwenger | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hola</main>

      <footer></footer>
    </div>
  );
}
